nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
    - '/etc/nginx/vhost.d'
    - '/usr/share/nginx/html'

www:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - './www:/usr/share/nginx/html:ro'
  environment:
    - VIRTUAL_HOST=hola.sosafernando.com


www2:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - './www2:/usr/share/nginx/html:ro'
  environment:
    - VIRTUAL_HOST=hola2.sosafernando.com


www3:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - './www2:/usr/share/nginx/html:ro'
  environment:
    - VIRTUAL_HOST=hola2.fec.sosafernando.com

